=== lracz/Webkonyvtarak/CI880V_0319/XDMCI880V.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:complexType name="etteremTipus">
    <xs:sequence>
      <xs:element name="nev" type="xs:string" />
      <xs:element name="cim" type="cimTipus" />
      <xs:element name="csillag" type="xs:integer" />
    </xs:sequence>
    <xs:attribute name="ekod" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="vendegTipus">
    <xs:sequence>
      <xs:element name="nev" type="xs:string" />
      <xs:element name="eletkor" type="xs:integer" />
      <xs:element name="cim" type="cimTipus" />
    </xs:sequence>
    <xs:attribute name="vkod" type="xs:string" use="required" />
  </xs:complexType>
  
  <xs:complexType name="cimTipus">
    <xs:sequence>
      <xs:element name="varos" type="xs:string" />
      <xs:element name="utca" type="xs:string" />
      <xs:element name="hazszam" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="foszakacsTipus">
    <xs:sequence>
      <xs:element name="nev" type="xs:string" />
      <xs:element name="eletkor" type="xs:integer" />
      <xs:element name="vegzettseg" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="fkod" type="xs:string" use="required" />
    <xs:attribute name="e_f" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="gyakornokTipus">
    <xs:sequence>
      <xs:element name="nev" type="xs:string" />
      <xs:element name="gyakorlat" type="gyakorlattipus" />
      <xs:element name="muszak" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="gkod" type="xs:string" use="required" />
    <xs:attribute name="e_gy" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="gyakorlattipus">
    <xs:sequence>
      <xs:element name="kezdete" type="xs:string" />
      <xs:element name="idotartama" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="szakacsTipus">
    <xs:sequence>
      <xs:element name="nev" type="xs:string" />
      <xs:element name="reszleg" type="xs:string" />
      <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="skod" type="xs:string" use="required" />
    <xs:attribute name="e_sz" type="xs:string" use="required" />
  </xs:complexType>


  <xs:complexType name="rendelesTipus">
    <xs:sequence>
      <xs:element name="osszeg" type="xs:integer" />
      <xs:element name="etel" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="rkod" type="xs:string" use="required" />
    <xs:attribute name="e_v_e" type="xs:string" use="required" />
    <xs:attribute name="e_v_v" type="xs:string" use="required" />
  </xs:complexType>

  <xs:element name="vendeglatas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="etterem" type="etteremTipus" maxOccurs="unbounded"> </xs:element>
        <xs:element name="foszakacs" type="foszakacsTipus" maxOccurs="unbounded"> </xs:element>
        <xs:element name="szakacs" type="szakacsTipus" maxOccurs="unbounded"> </xs:element>
        <xs:element name="gyakornok" type="gyakornokTipus" maxOccurs="unbounded"> </xs:element>
        <xs:element name="vendeg" type="vendegTipus" maxOccurs="unbounded"> </xs:element>
        <xs:element name="rendeles" type="rendelesTipus" maxOccurs="unbounded"> </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="etterem_kulcs">
      <xs:selector xpath="etterem" />
      <xs:field xpath="@ekod" />
    </xs:key>
    <xs:key name="foszakacs_kulcs">
      <xs:selector xpath="foszakacs" />
      <xs:field xpath="@fkod" />
    </xs:key>
    <xs:key name="szakacs_kulcs">
      <xs:selector xpath="szakacs" />
      <xs:field xpath="@skod" />
    </xs:key>
    <xs:key name="gyakornok_kulcs">
      <xs:selector xpath="gyakornok" />
      <xs:field xpath="@gkod" />
    </xs:key>
    <xs:key name="vendeg_kulcs">
      <xs:selector xpath="vendeg" />
      <xs:field xpath="@vkod" />
    </xs:key>
    <xs:key name="rendeles_kulcs">
      <xs:selector xpath="rendeles" />
      <xs:field xpath="@rkod" />
    </xs:key>

    <xs:keyref name="etterem_idegen_kulcs" refer="etterem_kulcs">
      <xs:selector xpath="rendeles" />
      <xs:field xpath="@e_v_e" />
    </xs:keyref>
    <xs:keyref name="vendeg_idegen_kulcs" refer="vendeg_kulcs">
      <xs:selector xpath="rendeles" />
      <xs:field xpath="@e_v_v" />
    </xs:keyref>
    <xs:keyref name="etterem_foszakacs_idegen_kulcs" refer="etterem_kulcs">
      <xs:selector xpath="foszakacs" />
      <xs:field xpath="@e_f" />
    </xs:keyref>
    <xs:keyref name="etterem_szakacs_idegen_kulcs" refer="etterem_kulcs">
      <xs:selector xpath="szakacs" />
      <xs:field xpath="@e_sz" />
    </xs:keyref>
    <xs:keyref name="etterem_gyakornok_idegen_kulcs" refer="etterem_kulcs">
      <xs:selector xpath="gyakornok" />
      <xs:field xpath="@e_gy" />
    </xs:keyref>
    <xs:unique name="unique_foszakacs">
      <xs:selector xpath="foszakacs" />
      <xs:field xpath="@e_f" />
    </xs:unique>

  </xs:element>

</xs:schema>

=== lracz/Webkonyvtarak/CI880V_0319/XMLCI880V.xml
<?xml version="1.0" encoding="UTF-8"?>
<vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XDMCI880V.xsd">
    <etterem ekod="E01">
        <nev>Gourmet Palota</nev>
        <cim>
            <varos>Budapest</varos>
            <utca>Sas utca</utca>
            <hazszam>12</hazszam>
        </cim>
        <csillag>5</csillag>
    </etterem>

    <foszakacs fkod="F01" e_f="E01">
        <nev>Gordon Ramsey</nev>
        <eletkor>50</eletkor>
        <vegzettseg>Magyar konyha</vegzettseg>
    </foszakacs>

    <szakacs skod="SZ01" e_sz="E01">
        <nev>Varga István</nev>
        <reszleg>R01</reszleg>
        <vegzettseg>Nemzetközi konyha</vegzettseg>
    </szakacs>

    <szakacs skod="SZ02" e_sz="E01">
        <nev>Farkas Gábor</nev>
        <reszleg>R01</reszleg>
        <vegzettseg>Magyar konyha</vegzettseg>
    </szakacs>

    <gyakornok gkod="GY01" e_gy="E01">
        <nev>Szabó Anna</nev>
        <gyakorlat>
            <kezdete>2023-10-01</kezdete>
            <idotartama>4 hónap</idotartama>
        </gyakorlat>
        <muszak>13:00 - 21:00</muszak>
    </gyakornok>

    <vendeg vkod="V01">
        <nev>Kovács Péter</nev>
        <eletkor>30</eletkor>
        <cim>
            <varos>Budapest</varos>
            <utca>Sas utca</utca>
            <hazszam>12</hazszam>
        </cim>
    </vendeg>

    <vendeg vkod="V02">
        <nev>Nagy János</nev>
        <eletkor>28</eletkor>
        <cim>
            <varos>Budapest</varos>
            <utca>Andrássy út</utca>
            <hazszam>50</hazszam>
        </cim>
    </vendeg>

    <rendeles rkod="REN001" e_v_e="E01" e_v_v="V01">
        <osszeg>12500</osszeg>
        <etel>Bécsi szelet burgonyapürével</etel>
    </rendeles>

    <rendeles rkod="REN002" e_v_e="E01" e_v_v="V02">
        <osszeg>8900</osszeg>
        <etel>Cézár saláta csirkemellel</etel>
    </rendeles>
</vendeglatas>
